pierres_folles/course/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from pierres_folles.course.views import RunnerView, InstantPaymentNotificationView, InscriptionsXlsView, ClassementView


urlpatterns = [
    url(
        r'^inscription/$',
        RunnerView.as_view(),
        name="course_inscription"
    ),

    url(
        r'^ipn/(?P<contact_uuid>[\w\d-]+)$',
        InstantPaymentNotificationView.as_view(),
        name='course_instant_payment_notification'
    ),

    url(
        r'^export-inscriptions/$',
        InscriptionsXlsView.as_view(),
        name='course_export_inscriptions'
    ),

    url(
        r'classement/$',
        ClassementView.as_view(),
        name='course_classement'
    ),
]

pierres_folles/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from balafon.urls import urlpatterns as balafon_urlpatterns
from pierres_folles.course import urls as course_urls

from django.contrib import admin
admin.autodiscover()

#from coop_cms.feeds import ArticleFeed
#class ArticleFeed(ArticleFeed):
#    title = "Apidev"
#    link = "/rss/"

urlpatterns = [

    url(r'^', include('coop_cms.sitemap')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^course/', include(course_urls)),

    url(
        r'^photos/$',
        RedirectView.as_view(url=reverse_lazy(u'pl-gallery-list', args=[1]), permanent=False),
        name='pl-photologue-root'
    ),

    url(
        r'^photos/gallery/$',
        RedirectView.as_view(url=reverse_lazy(u'pl-gallery-list', args=[1]), permanent=False),
        name='pl-photologue-root'
    ),

    url(r'^photos/', include('photologue.urls')),
]

urlpatterns += balafon_urlpatterns

sou/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib.admindocs import urls as admindocs_urls

from balafon.urls import urlpatterns as balafon_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^', include('coop_cms.sitemap')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include(admindocs_urls)),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
]

urlpatterns += balafon_urlpatterns

pierres_folles/course/models.py
# -*- coding: utf-8 -*-

from datetime import datetime, date, time, timedelta

from django.db import models
from django.utils.translation import ugettext_lazy as _

from django_extensions.db.models import TimeStampedModel

from balafon.Crm.models import Contact


class Partner(models.Model):
    """Sponsors"""
    name = models.CharField(max_length=100, verbose_name=_(u'Nom'))
    url = models.URLField(default='', blank=True, verbose_name=_(u'URL'))
    logo = models.ImageField(blank=True, upload_to='partners', default='', verbose_name=_(u'logo'))
    is_archived = models.BooleanField(default=True, verbose_name=_(u'archivé'))
    best_partner = models.BooleanField(default=False, verbose_name=_(u'partenaire majeur'))
    ordering = models.IntegerField(default=0, verbose_name=_(u"order d'affichage"))

    class Meta:
        verbose_name = _(u'Sponsor')
        verbose_name_plural = _(u'Sponsors')
        ordering = ('name',)

    def __str__(self):
        return self.name


class License(models.Model):
    name = models.CharField(max_length=200, verbose_name=_(u"Nom"))
    nb_required = models.BooleanField(default=True, verbose_name=_(u"No de license requis"))
    short_name = models.CharField(max_length=100, verbose_name=_(u"Nom court"), default='', blank=True)

    class Meta:
        verbose_name = _(u'Licence')
        verbose_name_plural = _(u'Licence')
        ordering = ('id',)

    def __str__(self):
        return self.name


class Competition(models.Model):
    name = models.CharField(max_length=100, verbose_name=_(u"Nom"))
    price = models.DecimalField(verbose_name=_(u'Prix Jour J'), max_digits=5, decimal_places=2)
    price_before = models.DecimalField(verbose_name=_(u'Prix pré-inscription'), max_digits=5, decimal_places=2)
    before_date = models.DateField(verbose_name=_(u'Date limite pré-inscription'))
    is_archived = models.BooleanField(default=False)

    class Meta:
        verbose_name = _(u'Competition')
        verbose_name_plural = _(u'Competitions')
        ordering = ('id',)

    def __str__(self):
        return self.name


class InfoSource(models.Model):
    """Comment un coureur a connu la course"""
    name = models.CharField(max_length=100, verbose_name=_(u"Nom"))
    ordering = models.IntegerField(default=0)

    class Meta:
        verbose_name = _(u"Source d'information")
        verbose_name_plural = _(u"Source d'informations")
        ordering = ('ordering', 'id')

    def __str__(self):
        return self.name


class Runner(Contact):
    """"""
    competition = models.ForeignKey(Competition, verbose_name=_(u"Course"))
    club = models.CharField(max_length=100, verbose_name=_(u"Club"), blank=True, default="")
    license = models.ForeignKey(
        License, default=None, blank=True, null=True, verbose_name=_(u"Licence"),
        help_text=_(
            u"Si vous n'êtes pas licencié, sélectionnez 'Cerificat médical'"
        )
    )
    license_number = models.CharField(max_length=100, default='', blank=True, verbose_name=_(u"N° de licence"))
    scan = models.FileField(
        upload_to="licenses", verbose_name=_(u"Fichier"),
        help_text=_(
            u"Joindre un scan de la license sportive ou du certificat médical. "
            u"Merci de ne pas dépasser 2Mo comme taille de fichier."
        )
    )
    payment_url = models.TextField(default='', blank=True)
    source_info = models.ForeignKey(InfoSource, default=None, null=True, on_delete=models.SET_NULL)

    def get_price(self):
        if self.runner.created.date() < self.competition.before_date:
            return self.competition.price_before
        else:
            return self.competition.price

    def get_payplug_amount(self):
        return int(self.get_price() * 100)

    class Meta:
        verbose_name = _(u'Participant')
        verbose_name_plural = _(u'Participants')
        ordering = ('lastname', 'firstname')


class InstantPaymentNotification(TimeStampedModel):
    """track every PayPlug IPN"""
    runner = models.ForeignKey(Runner)
    body = models.TextField(default='', blank=True)
    signature = models.TextField(default='', blank=True)
    is_ssl_valid = models.BooleanField(default=False, verbose_name=_(u'SSL message is ok'))
    is_amount_valid = models.BooleanField(default=False, verbose_name=_(u'received amount is ok'))
    is_email_valid = models.BooleanField(default=False, verbose_name=_(u'received email is ok'))
    is_contact_valid = models.BooleanField(default=False, verbose_name=_(u'received customer id is ok'))
    transaction_id = models.IntegerField(default=0)
    signature_ok = models.BooleanField(default=False)

    def __str__(self):
        return u'{0}'.format(self.runner)


class Category(models.Model):

    name = models.CharField(max_length=100)
    year1 = models.IntegerField()
    year2 = models.IntegerField()

    class Meta:
        verbose_name = _(u'Category')
        verbose_name_plural = _(u'Categories')
        ordering = ('year1',)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=100)
    heure_depart = models.TimeField(default=time(16, 0))

    def __str__(self):
        return self.name


class Inscrit(models.Model):
    GENDER_CHOICE = (
        (Contact.GENDER_MALE, u'Homme'),
        (Contact.GENDER_FEMALE, u'Femme'),
    )

    numero = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    gender = models.IntegerField(choices=GENDER_CHOICE)
    birth_date = models.DateField()
    category = models.ForeignKey(Category, blank=True, default=None, null=True)
    arrivee = models.TimeField(blank=True, null=True, default=None)
    contact = models.ForeignKey(Contact, default=None, blank=True, null=True)
    city = models.CharField(default='', max_length=100, blank=True)
    zip_code = models.CharField(default='', max_length=100, blank=True)
    email = models.EmailField(default='', blank=True)
    club = models.CharField(default='', max_length=100, blank=True)
    phone = models.CharField(default='', max_length=100, blank=True)

    class Meta:
        verbose_name = _(u'Inscrit')
        verbose_name_plural = _(u'Inscrits')
        ordering = ('numero', 'nom', 'prenom', 'arrivee')

    def __str__(self):
        return u'{0} - {1}'.format(self.numero, self.nom)

    def fullname(self):
        return u'{0} {1}'.format(self.nom, self.prenom)

    def temps(self):
        if self.arrivee:
            heure_arrivee = self.arrivee
        else:
            heure_arrivee = datetime.now().time()
        dt2 = datetime.combine(date.today(), heure_arrivee)
        dt1 = datetime.combine(date.today(), self.course.heure_depart)
        return dt2 - dt1

    def calcul_categorie(self):
        if self.category:
            return self.category
        categories = list(Category.objects.all().order_by('year1'))
        for cat in categories:
            if self.birth_date.year >= cat.year1 and self.birth_date.year <= cat.year2:
                return cat
        return None

    def save(self, *args, **kwargs):
        self.category = self.calcul_categorie()
        return super(Inscrit, self).save(*args, **kwargs)

pierres_folles/course/forms.py
# -*- coding: utf-8 -*-

from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

import floppyforms as forms
from balafon.Crm.models import Contact
from balafon.Crm.forms import ModelFormWithCity


from pierres_folles.course.models import Runner, Competition


class RunnerForm(ModelFormWithCity):
    """formulaire d'inscription"""

    GENDER_CHOICES = (
        ('', _(u'')),
        (Contact.GENDER_MALE, _(u'Mr')),
        (Contact.GENDER_FEMALE, _(u'Mrs')),
    )

    accept_rules = forms.BooleanField(
        label=u"Je reconnais avoir pris connaissance du réglement et en accepte les modalités",
        help_text='Cocher la case pour accepter',
        required=True,
    )

    class Meta:
        model = Runner
        fields = (
            'gender', 'lastname', 'firstname', 'birth_date', 'email', 'address', 'zip_code', 'city', 'country', 'phone',
            'competition', 'club', 'license', 'license_number', 'scan', 'source_info', 'notes', 'accept_rules'
        )

    def __init__(self, *args, **kwargs):
        super(RunnerForm, self).__init__(*args, **kwargs)
        self.fields['country'].widget = forms.HiddenInput()
        self.fields['gender'].choices = RunnerForm.GENDER_CHOICES

        competition_queryset = Competition.objects.filter(is_archived=False)

        self.fields['competition'].queryset = competition_queryset

        required_fields = (
            'gender', 'lastname', 'firstname', 'birth_date', 'email', 'address', 'zip_code', 'city', 'phone', 'license',
        )
        for field in required_fields:
            self.fields[field].required = True

        self.fields['birth_date'].help_text = mark_safe(u'JJ/MM/AAAA &nbsp; &nbsp; &nbsp; exemple 14/02/1982')
        self.fields['license_number'].help_text = u'Seulement pour les licenciés'
        self.fields['club'].help_text = u'Seulement pour les licenciés'

        self.fields['notes'].label = u"Une question ou un message à nous laisser?"
        self.fields['notes'].help_text = u"Vous pouvez aussi nous dire quelles sont vos attentes pour cette course."

        self.fields['competition'].help_text = mark_safe(
            u'. &nbsp; - &nbsp; '.join(
                [
                    u'{0}: {1:02}€ avant le {2:%d/%m}, {3:02}€ après'.format(
                        competition.name,
                        competition.price_before,
                        competition.before_date,
                        competition.price
                    )
                    for competition in competition_queryset
                ]
            )
        )

    def clean_notes(self):
        notes = self.cleaned_data['notes']
        if len(notes) > 20000:
            raise forms.ValidationError("Votre commmentaire ne peut excéder 20000 caractères")
        return notes

pierres_folles/templates/_best_partners.html
{% load coop_utils thumbnail %}
<div class="partners">
  {% for partner in partners %}
  <div class="row my-row">
    <div class="col-sm-8 col-sm-offset-2">
      <div style="text-align: center;">
        <a class="partner" {% if partner.url %}href="{{ partner.url}}" target="_blank"{% endif %}>
          {% thumbnail partner.logo "900" as im %}
              <img src="{{ im.url }}" class="img-fluid" alt="{{ partner.name}}" title="{{ partner.name}}" />
          {% endthumbnail %}
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

pierres_folles/templates/_field.html
{% load i18n %}
<td{% if colspan %} colspan={{colspan}}{% endif %}>
  {% if field.errors %}
  <ul class="fielderror">
    <img src="{{STATIC_URL}}img/fielderror.png" class="fielderror-ico"/>
      {% for err in field.errors %}
          <li>{{err}}</li>
      {% endfor %}
  </ul>
  {% endif %}
  {{field}}
  {% if show_label %}{{field.label}}{% endif %}
  {% if field.help_text %}<div class="help-text">{{ field.help_text }}</div>{% endif %}
</td>

pierres_folles/templates/_partners.html
{% load coop_utils thumbnail %}
<div class="partners">
  {% for partner_line in partners|group_in_sublists:3 %}
  <div class="row my-row">
    {% for partner in partner_line %}
    <div class="col-sm-4">
      <div>
        <a class="partner" {% if partner.url %}href="{{ partner.url}}" target="_blank"{% endif %}>
          {% thumbnail partner.logo "300" as im %}
              <img src="{{ im.url }}" class="img-fluid" alt="{{ partner.name}}" title="{{ partner.name}}" />
          {% endthumbnail %}
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
</div>

pierres_folles/templates/base.html
<!DOCTYPE html>{% load i18n static coop_navigation coop_utils coop_bar_tags thumbnail coop_edition %}
<html lang="fr">
  <head>


    <meta charset="utf-8"/>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>La Course des Pierres Folles {% block extra_title %}{% endblock %}</title>

    <meta name="description" content="{% block description %}{% endblock %}">
	
    {% block jquery_declaration %}
	{% include "coop_cms/_js_includes.html" %}
	{% endblock %}
	
    <!-- Bootstrap core CSS -->
    <link href="{{STATIC_URL}}bs/css/bootstrap.css" rel="stylesheet">
	  <link rel="stylesheet" href="{{ STATIC_URL }}css/coop_cms.css?v=1.0" type="text/css" />
    <link href="{{STATIC_URL}}css/scrolling-nav.css" rel="stylesheet">

    <link href="{% versioned_static_file 'css/la-course-des-pierres-folles.css' %}" rel="stylesheet">

    <!-- Bootstrap Core JavaScript -->
    <script src="{{STATIC_URL}}bs/js/bootstrap.min.js"></script>

    <!-- Scrolling Nav JavaScript -->
    <script src="{{STATIC_URL}}js/jquery.easing.1.3.js"></script>
    <script src="{{STATIC_URL}}js/scrolling-nav.js"></script>
    <script src="/static/js/jquery-ui-1.9.2.js" charset="utf-8" type="text/javascript"></script>
    <link href="{{STATIC_URL}}css/base/jquery-ui-1.9.2.css" rel="stylesheet" />
    <script type="text/javascript" src="https://www.openlayers.org/api/OpenLayers.js"></script>
    <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v3.3.0/css/ol.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

	{% coop_bar_headers %}
	{% block extra_head %}{% endblock %}
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.4&appId=628712167150475";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

	{% include "coop_cms/_messages.html" %}
<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

    {% block navigation %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/">
                  <img src="{{ STATIC_URL}}img/la-course-des-pierres-folles.png" title="La Course des Pierres Folles" alt="La Course des Pierres Folles" />
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>

                    {% block cms_navigation %}
                    {% navigation_as_nested_ul tree='top' css_class="page-scroll" %}
                    {% endblock cms_navigation %}

                    <li class="fb-like-in-menu">
                      <a>
                        <div
                          class="fb-like" data-layout="button_count" data-href="https://www.facebook.com/lacoursedespierresfolles">
                        </div>
                      </a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    {% endblock %}

    <div class="container-liquid">
        <div class="row"><div class="col-sm-12">
        {% block content %}
            {% block document %} {% endblock %}
        {% endblock %}
        </div></div>

        <div class="footer">
          <div class="row">

            <div class="col-sm-3 col-sm-offset-1">
              {% coop_piece_of_html "Contact" read_only=1 %}
            </div>

            <div class="col-sm-4">
              <h4>Suivez-nous</h4>
              <ul class="footer-nav">
                {% navigation_as_nested_ul tree='footer' %}
                <li>&nbsp;</li>
                <li>
                  <div class="fb-like" data-layout="standard" data-show-faces="true"
                  data-href="https://www.facebook.com/lacoursedespierresfolles"
                  data-colorscheme="dark"
                  ></div>
                </li>
              </ul>

            </div>

            <div class="col-sm-2  col-sm-offset-1">
              <div class="pull-right">
              <div>{% include "coop_cms/_social_share.html" %}</div>
              </div>
            </div>
          </div>
        </div>

    </div>

	{% coop_bar %}

	{% if debug or request.user.is_staff %}
	<div class=".analytics" style="color: orange; font-size: small; float: right;">
		{% if request.user.is_staff %}Staff{% else %}Debug{% endif %}: Google Analytics disabled
	</div>
	{% else %}
		<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-9579717-7', 'auto');
      ga('send', 'pageview');

    </script>
	</script>
	{% endif %}

</body>
</html>

pierres_folles/templates/homepage.html
{% extends "coop_cms/article.html" %}

{% load coop_edition thumbnail coop_utils coop_navigation i18n %}

{% block cms_navigation %}
{% navigation_as_nested_ul css_class="page-scroll" %}
{% endblock cms_navigation %}

{% block extra_head %}
    {{ block.super }}
    {{ runner_form.media }}

    <!--<script>-->
      <!--function openInNewTab(url) {-->
          <!--var win = window.open(url, '_blank');-->
          <!--win.focus();-->
      <!--}-->

      <!--window.onload = function() {-->
        <!--var rozierLatLng = new google.maps.LatLng(45.80859,4.270556);-->
        <!--var myOptions = {-->
            <!--center: rozierLatLng,-->
            <!--zoom: 9,-->
            <!--mapTypeId: google.maps.MapTypeId.ROADMAP,-->
            <!--disableDefaultUI: true,-->
            <!--scrollwheel: false,-->
            <!--navigationControl: true,-->
            <!--mapTypeControl: false,-->
            <!--scaleControl: false,-->
            <!--draggable: false-->
        <!--};-->

        <!--var map = new google.maps.Map(document.getElementById("map"), myOptions);-->

        <!--var marker = new google.maps.Marker({-->
            <!--position: rozierLatLng,-->
            <!--map: map,-->
            <!--title: 'Rozier en Donzy',-->
            <!--label: 'Rozier en Donzy',-->
        <!--});-->

        <!--google.maps.event.addListener(marker, 'click', function() {-->
          <!--openInNewTab('https://goo.gl/maps/5SqEB');-->
        <!--});-->

        <!--$(".article-logo img").addClass('img-responsive');-->

        <!--$("#id_city").addClass('form-control');-->

    <!--}-->
    <!--</script>-->

{% endblock %}


{% block document %}
    {% cms_edit article %}

    <!-- Intro Section -->
    <section id="about" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="article-logo">{{ article.logo }}</div>
                    <h1>{{ article.title }}</h1>
                </div>
            </div>

            <div class="row">
              <div class="col-sm-6">
                {{ article.content }}
              </div>

              <div class="col-sm-6">
                <div class="le-sou">
                {% coop_piece_of_html "Sou" %}
                </div>


                <div style="margin-top: 30px; text-align: right;">
                  <div
                    class="fb-like" data-layout="standard" data-show-faces="true"
                    data-href="https://www.facebook.com/lacoursedespierresfolles"
                  ></div>
                </div>

                <div class="email-subscribe" style="margin-top: 30px;">
                  <h4>Inscription Newsletter</h4>
                  <p>Restez informés des actualités de la course en nous suivant sur Facebook
                    et en vous inscrivant à notre newsletter.</p>
                  <iframe src="{% url 'emailing_email_subscribe_subscription' 1 %}" width=100%" height="100px" frameborder=0></iframe>
                </div>

              </div>





            </div>

            <div class="row">

              <div class="col-sm-12">
                <div class="pull-right">

                </div>
              </div>
            </div>

        </div>
        </div>
    </section>

    <section id="rozier" class="rozier-section">
        <div class="container">
            <div class="row">

              <div class="col-sm-6">
                {% coop_piece_of_html "Rozier" %}
              </div>

              <div class="col-sm-4 col-sm-offset-1">
                  <div id="map" style="width:350px; height: 350px"></div>
              </div>
                <script>
                  var map = new OpenLayers.Map('map');
                  var mapnik = new OpenLayers.Layer.OSM();
                  map.addLayer(mapnik);
                  var center = new OpenLayers.LonLat(4.270556, 45.80859) // Centre de la carte
                  .transform(
                      new OpenLayers.Projection("EPSG:4326"), // transformation de WGS 1984
                      new OpenLayers.Projection("EPSG:900913") // en projection Mercator sphérique
                  );
                  var zoom = 12;
                  var marker_layer = new OpenLayers.Layer.Markers( "Markers" );
                  marker = new OpenLayers.Marker(center);
                  marker.events.register('mouseover', marker, function(evt) {
                      popup = new OpenLayers.Popup.FramedCloud("Popup",
                          center,
                          null,
                          '<div class="info_bulle"><p>Les Pierres Folles</p></div>',
                          null,
                          false
                      );
                      map.addPopup(popup);
                  });
                  //here add mouseout event
                  marker.events.register('mouseout', marker, function(evt) {
                      popup.hide();
                  });
                  marker_layer.addMarker(marker);
                  map.addLayer(marker_layer);
                  map.setCenter(center, zoom);
                </script>
            </div>
        </div>

    </section>

    <section class="photo-section">

      {% coop_image_list 'Album Homepage' as homepage_album %}
      <div class="row">
        <div class="col-sm-12 homepage-carousel">
          {% include "coop_bootstrap/carousel.html" with image_list=homepage_album %}
        </div>
      </div>

    </section>


    <section class="partenaires-section">
      <div id="partenaires" class="container">
        <div class="row">
          <div class="col-sm-12">
            <h3>Sponsors</h3>
          </div>
        </div>

        {% include "_best_partners.html" with partners=primary_partners %}
        {% include "_partners.html" with partners=secondary_partners %}

      </div>
    </section>


    {% coop_fragments "homepage_section" template_name="homepage_section.html" %}

    {% end_cms_edit %}

    {% if inscription_active %}
    <section class="inscription-section">
      <div id="inscriptions" class="container">
        <div class="row">
          <div class="col-sm-12">
            <h3>Inscription</h3>

            <form role="form" action="{% url 'course_inscription' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <ul class="inscription-form">{{ runner_form.as_ul }}</ul>

            <div class="row">
              <div class="col-sm-12">
                <div class="pull-right">
                  <input type="submit" class="btn btn-primary align-right" value="S'inscrire et Payer">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <div class="helptext" style="text-align: right;">
                  Vous serez redirigé vers le site de PayPlug, notre partenaire bancaire
                </div>
              </div>
            </div>

          </form>


          </div>
        </div>
      {% endif %}

    {% if_cms_edition %}
    {% include "coop_cms/_article_publication.html" %}
    {% endif %}
{% endblock %}

pierres_folles/templates/homepage_section.html
{% load coop_utils %}
<!-- Section -->
<section id="{{ name }}" class="{{ name }}-section {{ css_class }}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
            	{{ fragment|safe }}
            </div>
        </div>
    </div>
</section>

pierres_folles/templates/standard.html
{% extends "coop_cms/article.html" %}

{% load coop_edition coop_utils i18n %}


{% block article %}
{% cms_edit article %}

<section id="intro" class="intro-section">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="article-logo">{{ article.logo }}</div>
        <h1 class="article-title">{{ article.title }}</h1>
        <div class="article-content">{{ article.content }}</div>
      </div>
    </div>
  </div>
</section>
{% end_cms_edit %}
	
{% if_cms_edition %}
{% include "coop_cms/_article_publication.html" %}
{% endif %}

{% endblock %}